const ActionFunctionStatusEnum = {
  //EXTERNAL
  //top level SUCCESS
  SUCCESS: "SUCCESS",
  SUCCESS_NO_DATA: "SUCCESS_NO_DATA",
  //top level ERROR
  //these errors will populate an error object with an error type and error message
  ERROR: "ERROR",
  ERROR_MISSING_INPUT: "ERROR_MISSING_INPUT",
  ERROR_INVALID_INPUT: "ERROR_INVALID_INPUT",
  ERROR_MISSING_OUTPUT_DATA: "ERROR_MISSING_OUTPUT_DATA",
  ERROR_INVALID_OUTPUT_DATA: "ERROR_INVALID_OUTPUT_DATA",
  ERROR_BAD_REQUEST: "ERROR_BAD_REQUEST",
  ERROR_TIMEOUT: "ERROR_TIMEOUT",
  ERROR_INVALID_CREDENTIALS: "ERROR_INVALID_CREDENTIALS"
}

module.exports = ActionFunctionStatusEnum